import torch
from torch.nn import Module
from utils.logits_processor import LogitsProcessor, GreedyProcessor
from transformers.cache_utils import DynamicCache
from utils.caching import prune_cache, prune_dynamic_cache
import utils.printing as printing
from typing import List, Tuple


def max_fn(x: torch.Tensor) -> torch.Tensor:
    """
    Max function.
        x: input tensor.
    Returns:
        tensor norm(max(0, x)).
    """
    x_max = torch.where(x > 0, x, torch.zeros_like(x))
    x_max_sum = torch.sum(x_max, dim=-1, keepdim=True)
    return x_max / x_max_sum


@torch.no_grad()
def speculative_generate(
    inputs: List[int],
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
) -> Tuple[List[int], float]:
    """
    Generate text sequence using the speculative decoding algorithm.
    Implementation of Speculative Decoding. (https://arxiv.org/pdf/2211.17192.pdf)
    
    Args:
        inputs (List[int]): input sequence of batch size 1.
        drafter (Module): drafter model.
        target (Module): target model.
        tokenizer: tokenizer (used for debugging).
        gamma (int): number of drafts generated by the drafter at each step.
        logits_processor (LogitsProcessor): logits processor for sampling.
        max_gen_len (int): maximum length of the generated sequence.
        eos_tokens_id (int or List[int]): end token id (could be multiple).
        pad_token_id (int): pad token id.
        use_cache (bool): whether to use cache.
        skip_sample_adjustment (bool): whether to skip the sample adjustment step when some drafts are discarded.
        first_target (bool): whether to run the target model before the speculative algorithm.
        debug (bool): debug mode.
    
    Returns:
        List[int]: generated sequence.
        float: acceptance rate (number of accepted drafts divided by the number of total drafts).
        
    Note: This generation methods only works for decoder-only models.
    Note bis: The drafter and target models should output the same logits shape.
    Note ter: NgramModels are currently not supported.
    """
    
    drafter_cache, target_cache = None, None

    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    drafts_accepted, drafts_speculated = .0, .0
    
    vocabulary_size = target.config.vocab_size    
        
    # prepare input tensor
    prompt_len = len(inputs)
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = torch.tensor(inputs, dtype=torch.long, device=target.device)
    
    current_position = prompt_len
    
    if first_target:
        # run the target model before the speculative algorithm. Allows to prefill the kvcache and get a first token.
        Mp = target(
            input_ids=input_ids[..., :current_position],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        p_p = logits_processor(Mp.logits[..., -1, :])
        t = logits_processor.sample(p_p)
        input_ids[0, current_position] = t
        current_position += 1
        
        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return input_ids[0, prompt_len:current_position].tolist(), 0
        
        if debug:
            printing.initial_step(t, tokenizer)
    
    while current_position < total_len:
        corrected_gamma = min(gamma, total_len - current_position - 1)
        q = torch.zeros((1, corrected_gamma, vocabulary_size), device=target.device)
        
        input_ids = input_ids.to(drafter.device)
        
        # generate gamma drafts
        for k in range(corrected_gamma):
            Mq = drafter(
                input_ids=input_ids[..., :current_position + k],
                past_key_values=drafter_cache,
                use_cache=use_cache,
            )
            drafter_cache = Mq.past_key_values
            
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = logits_processor(draft_logits)
            q[0, k] = draft_probs.to(target.device)
            xi = logits_processor.sample(draft_probs)
            input_ids[0, current_position + k] = xi
        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)
        
        # run target model on drafts and get logits of the previous tokens plus one more token
        Mp = target(
            input_ids=input_ids[..., :current_position + corrected_gamma],
            past_key_values=target_cache,
            use_cache=use_cache,
        )
        target_cache = Mp.past_key_values
        draft_logits = Mp.logits[..., current_position - 1:current_position + corrected_gamma - 1, :] # [1, corrected_gamma, vocab_size]
        p = logits_processor(draft_logits) # [1, gamma, vocab_size]
        
        # compute the last accepted draft position (rejection sampling)
        r = torch.rand(corrected_gamma, device=target.device)
        fractions = p / q
        n = corrected_gamma
        for i in range(corrected_gamma):
            if r[i] > fractions[0, i, input_ids[0, current_position + i]]:
                n = i
                break
        
        drafts_accepted += n
        
        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + n], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return input_ids[0, prompt_len:current_position + stop_location + 1].tolist(), drafts_accepted / drafts_speculated

        # adjust the distribution from Mp
        if n == corrected_gamma:
            p_p = Mp.logits[..., current_position + corrected_gamma - 1, :]
            p_p = logits_processor(p_p)
        else:
            # prune the cache
            if use_cache:
                drafter_cache = prune_cache(drafter_cache, corrected_gamma - n)
                target_cache = prune_cache(target_cache, corrected_gamma - n + 1)
            
            if not skip_sample_adjustment:
                p_p = max_fn(p[..., n, :] - q[0, n, :])
            else:
                p_p = p[..., n, :]
        x = logits_processor.sample(p_p)
        
        if debug:
            generated = input_ids.clone().detach()
            
        input_ids[0, current_position + n:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + n] = x
        
        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, n, prompt_len, current_position, corrected_gamma)
            
        current_position += n + 1
        
        if torch.isin(x, stop_tokens):
            if debug:
                printing.end_token_found(n)
            return input_ids[0, prompt_len:current_position].tolist(), drafts_accepted / drafts_speculated
    
    return input_ids[0, prompt_len:].tolist(), drafts_accepted / drafts_speculated


@torch.no_grad()
def speculative_generate_llama_vision(
    inputs,
    drafter: Module,
    target: Module,
    tokenizer = None,
    gamma: int = 5,
    logits_processor: LogitsProcessor = GreedyProcessor(),
    max_gen_len: int = 40,
    eos_tokens_id: int | List[int] = 1,
    pad_token_id: int = 0,
    use_cache: bool = False,
    skip_sample_adjustment: bool = False,
    first_target: bool = True,
    debug: bool = False,
    drafter_cache: DynamicCache = None,
    target_cache: DynamicCache = None,
) -> Tuple[List[int], float, DynamicCache, DynamicCache]:


    list_tokens_id = eos_tokens_id if isinstance(eos_tokens_id, list) else [eos_tokens_id]
    stop_tokens = torch.tensor(list_tokens_id, dtype=torch.long, device=target.device).unsqueeze(1)
    
    drafts_accepted, drafts_speculated = .0, .0
    
    vocabulary_size = target.config.text_config.vocab_size

    # prepare input tensor
    prompt_len = len(inputs["input_ids"][0])
    max_seq_length = target.config.max_position_embeddings if hasattr(target.config, 'max_position_embeddings') else (target.config.max_context_length if hasattr(target.config, 'max_context_length') else 1024)
    total_len = min(max_seq_length, prompt_len + max_gen_len)
    input_ids = torch.full((1, total_len), pad_token_id, dtype=torch.long, device=target.device)
    input_ids[0, :prompt_len] = inputs["input_ids"][0].to(dtype=torch.long, device=target.device)
    
    current_position = prompt_len

    Mp = target(
        input_ids=input_ids[..., :current_position],
        past_key_values=target_cache,
        use_cache=True,
        attention_mask=inputs["attention_mask"],
        cross_attention_mask=inputs["cross_attention_mask"],
        pixel_values=inputs["pixel_values"],
        aspect_ratio_ids=inputs["aspect_ratio_ids"],
        aspect_ratio_mask=inputs["aspect_ratio_mask"],
    )
    target_cache = Mp.past_key_values

    input_ids = input_ids.to(drafter.device)
    Mq = drafter(
        input_ids=input_ids[..., :current_position],
        past_key_values=drafter_cache,
        use_cache=True,
        attention_mask=inputs["attention_mask"],
        cross_attention_mask=inputs["cross_attention_mask"],
        pixel_values=inputs["pixel_values"],
        aspect_ratio_ids=inputs["aspect_ratio_ids"],
        aspect_ratio_mask=inputs["aspect_ratio_mask"],
    )
    drafter_cache = Mq.past_key_values

    draft_num_input = 1

    if first_target:
        input_ids = input_ids.to(target.device)
        p_p = logits_processor(Mp.logits[..., -1, :])
        t = logits_processor.sample(p_p)
        input_ids[0, current_position] = t
        current_position += 1
        
        if torch.isin(t, stop_tokens):
            if debug:
                printing.end_token_found(0)
            return input_ids[0, prompt_len:current_position].tolist(), 0
        
        if debug:
            printing.initial_step(t, tokenizer)
    
    while current_position < total_len:

        corrected_gamma = min(gamma, total_len - current_position - 1)
        q = torch.zeros((1, corrected_gamma, vocabulary_size), device=target.device)
        input_ids = input_ids.to(drafter.device)
        
        for k in range(corrected_gamma):
            draft_model_input = input_ids[..., current_position + k - draft_num_input : current_position + k]
            total_input = input_ids[..., :current_position + k] 
            draft_attention_mask=torch.ones((1, total_input.shape[1])).contiguous().to(target.device)
            draft_cross_attention_mask=torch.ones((1, draft_model_input.shape[1], 1, 4)).contiguous().to(target.device)
            Mq = drafter(
                input_ids=draft_model_input,
                past_key_values=drafter_cache,
                use_cache=True,
                attention_mask=draft_attention_mask,
                cross_attention_mask=draft_cross_attention_mask,
            )

            draft_num_input = 1

            drafter_cache = Mq.past_key_values
            draft_logits = Mq.logits[..., -1, :]
            draft_probs = logits_processor(draft_logits)
            q[0, k] = draft_probs.to(target.device)
            xi = logits_processor.sample(draft_probs)
            input_ids[0, current_position + k] = xi

        drafts_speculated += corrected_gamma
        input_ids = input_ids.to(target.device)
        
        # run target model on drafts and get logits of the previous tokens plus one more token
        target_model_input = input_ids[..., current_position-1:current_position + corrected_gamma]
        total_input = input_ids[..., :current_position + corrected_gamma]
        target_attention_mask=torch.ones((1, total_input.shape[1])).contiguous().to(target.device)
        target_cross_attention_mask=torch.ones((1, target_model_input.shape[1], 1, 4)).contiguous().to(target.device)

        Mp = target(
            input_ids=target_model_input,
            past_key_values=target_cache,
            use_cache=True,
            attention_mask=target_attention_mask,
            cross_attention_mask=target_cross_attention_mask,
        )

        target_cache = Mp.past_key_values
        draft_logits = Mp.logits[..., :-1, :]
        p = logits_processor(draft_logits)
        
        # compute the last accepted draft position (rejection sampling)
        r = torch.rand(corrected_gamma, device=target.device)
        fractions = p / q
        valid_tokens = corrected_gamma
        for i in range(corrected_gamma):
            target_token = logits_processor.sample(p[0, i, input_ids[0, current_position + i]])
            draft_token = logits_processor.sample(q[0, i, input_ids[0, current_position + i]])
            if r[i] > fractions[0, i, input_ids[0, current_position + i]] and target_token != draft_token:
                print(r[i], fractions[0, i, input_ids[0, current_position + i]], p[0, i, input_ids[0, current_position + i]], q[[0, i, input_ids[0, current_position + i]]])
                print(logits_processor(p[0, i, input_ids[0, current_position + i]]), logits_processor(q[[0, i, input_ids[0, current_position + i]]]))
                valid_tokens = i
                break
        
        drafts_accepted += valid_tokens
        
        # check if the end token is in the drafts
        stop_locations = torch.nonzero(torch.eq(input_ids[..., current_position:current_position + valid_tokens], stop_tokens))
        if stop_locations.shape[0] > 0:
            stop_location = stop_locations[0, 1].item()
            if debug:
                printing.end_token_found(stop_location)
            return input_ids[0, prompt_len:current_position + stop_location + 1].tolist(), drafts_accepted / drafts_speculated

        # adjust the distribution from Mp
        if valid_tokens == corrected_gamma:
            p_p = Mp.logits[...,- 1, :]
            p_p = logits_processor(p_p)
            draft_num_input = 2
        else:
            # prune the cache
            drafter_cache = prune_dynamic_cache(drafter_cache, corrected_gamma - valid_tokens, drafter.config.text_config.cross_attention_layers)
            target_cache = prune_dynamic_cache(target_cache, corrected_gamma - valid_tokens + 1, target.config.text_config.cross_attention_layers)
            draft_num_input = 1
            
            if not skip_sample_adjustment:
                p_p = p[..., valid_tokens, :] #p_p = max_fn(p[..., valid_tokens, :] - q[0, valid_tokens, :])
            else:
                p_p = p[..., valid_tokens, :]

        x = logits_processor.sample(p_p)
        
        if debug:
            generated = input_ids.clone().detach()
            
        input_ids[0, current_position + valid_tokens:current_position + corrected_gamma] = pad_token_id
        input_ids[0, current_position + valid_tokens] = x
        
        if debug:
            printing.speculative_step(tokenizer, generated, input_ids, valid_tokens, prompt_len, current_position, corrected_gamma)
            
        current_position += valid_tokens + 1
        
        if torch.isin(x, stop_tokens):
            if debug:
                printing.end_token_found(valid_tokens)
            return input_ids[0, prompt_len:current_position].tolist(), drafts_accepted / drafts_speculated
    
    return input_ids[0, prompt_len:].tolist(), drafts_accepted / drafts_speculated, drafter_cache, target_cache